import { defineWorkspaceRegistry } from "../../../shared/workspace-contract";

export const dashboardLedgerWorkspaceRegistry = defineWorkspaceRegistry({
  id: "dashboard.accounting-ledger",
  title: "Реестр объекта",
  description: "Рабочая область договорных сумм, план/факт оплат, счетов, актов и контрагентов.",
  components: [
    {
      id: "dashboard.ledger.scene-switch",
      type: "toolbar",
      title: "Переключатель сцен объекта",
      description: "Навигация внутри карточки объекта между паспортом, договором и реестром.",
      dataKey: "dashboard.activeView",
      area: { x: 1, y: 1, w: 30, h: 3 },
      minArea: { w: 12, h: 2 },
      priority: 80,
      capabilities: {
        movable: false,
        resizable: false,
        deletable: false,
        copyable: false,
        collapsible: false,
      },
      children: [
        {
          id: "dashboard.ledger.scene-switch.button",
          type: "button",
          role: "navigation",
          label: "Переключить сцену",
          dataKey: "dashboard.activeView",
          critical: true,
        },
      ],
      source: {
        feature: "dashboard/accounting",
        file: "project-accounting-workspace.tsx",
      },
    },
    {
      id: "dashboard.ledger.summary-strip",
      type: "summary",
      title: "Сводка реестра",
      description: "Договор, остаток, план, факт, работы и материалы по квадратному метру.",
      dataKey: "dashboard.project.accountingSummary",
      area: { x: 1, y: 4, w: 22, h: 6 },
      minArea: { w: 12, h: 4 },
      priority: 90,
      capabilities: {
        movable: false,
        resizable: true,
        deletable: false,
        copyable: false,
        collapsible: true,
      },
      children: [
        {
          id: "dashboard.ledger.summary.contract",
          type: "metric",
          role: "summary",
          label: "Договор",
          dataKey: "dashboard.project.contract.amount",
          critical: true,
        },
        {
          id: "dashboard.ledger.summary.plan",
          type: "metric",
          role: "summary",
          label: "План",
          dataKey: "dashboard.project.plannedTotal",
        },
        {
          id: "dashboard.ledger.summary.actual",
          type: "metric",
          role: "summary",
          label: "Факт",
          dataKey: "dashboard.project.actualTotal",
        },
      ],
      source: {
        feature: "dashboard/accounting",
        file: "project-accounting-summary-strip.tsx",
      },
    },
    {
      id: "dashboard.ledger.status-summary",
      type: "summary",
      title: "Статусы оплат",
      description: "Суммы и количество строк по счетам, ожиданию оплаты, оплате и плану.",
      dataKey: "dashboard.project.ledgerEntries.statusGroups",
      area: { x: 23, y: 4, w: 8, h: 6 },
      minArea: { w: 6, h: 4 },
      priority: 75,
      capabilities: {
        movable: false,
        resizable: true,
        deletable: false,
        copyable: false,
        collapsible: true,
      },
      children: [
        {
          id: "dashboard.ledger.status.invoice",
          type: "status",
          role: "status",
          label: "Счет",
          dataKey: "dashboard.project.ledgerEntries.invoiceTotal",
        },
        {
          id: "dashboard.ledger.status.paid",
          type: "status",
          role: "status",
          label: "Оплачено",
          dataKey: "dashboard.project.ledgerEntries.paidTotal",
        },
      ],
      source: {
        feature: "dashboard/accounting",
        file: "project-accounting-status-summary.tsx",
      },
    },
    {
      id: "dashboard.ledger.table",
      type: "table",
      title: "Строки реестра",
      description: "Категории, статьи расходов, контрагенты, статусы, счета и акты.",
      dataKey: "dashboard.project.ledgerEntries",
      area: { x: 1, y: 10, w: 30, h: 18 },
      minArea: { w: 18, h: 10 },
      priority: 100,
      capabilities: {
        movable: false,
        resizable: true,
        deletable: false,
        copyable: false,
        collapsible: false,
      },
      children: [
        {
          id: "dashboard.ledger.table.add-row",
          type: "button",
          role: "primary-action",
          label: "Добавить строку",
          dataKey: "dashboard.project.ledgerEntries",
          critical: true,
        },
        {
          id: "dashboard.ledger.table.delete-row",
          type: "confirm",
          role: "danger-action",
          label: "Удалить строку",
          dataKey: "dashboard.project.ledgerEntries",
          critical: true,
          capabilities: { deletable: true },
        },
        {
          id: "dashboard.ledger.table.category",
          type: "dropdown",
          role: "selector",
          label: "Категория",
          dataKey: "dashboard.project.ledgerEntries.category",
        },
        {
          id: "dashboard.ledger.table.counterparty",
          type: "dropdown",
          role: "selector",
          label: "Контрагент",
          dataKey: "dashboard.project.ledgerEntries.counterparty",
        },
        {
          id: "dashboard.ledger.table.status",
          type: "dropdown",
          role: "selector",
          label: "Статус оплаты",
          dataKey: "dashboard.project.ledgerEntries.status",
          critical: true,
        },
        {
          id: "dashboard.ledger.table.document",
          type: "dropdown",
          role: "selector",
          label: "Счет или акт",
          dataKey: "dashboard.project.ledgerEntries.documents",
        },
      ],
      relationships: [
        {
          type: "summarizes",
          targetId: "dashboard.ledger.summary-strip",
        },
        {
          type: "summarizes",
          targetId: "dashboard.ledger.status-summary",
        },
      ],
      source: {
        feature: "dashboard/accounting",
        file: "project-accounting-ledger-table.tsx",
      },
    },
  ],
});
