"""Create app users table.

Revision ID: 0002_create_app_users
Revises: 0001_initial_base
Create Date: 2026-05-13
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0002_create_app_users"
down_revision: str | None = "0001_initial_base"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute(
            """
            CREATE TABLE IF NOT EXISTS app_users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                email TEXT NOT NULL,
                display_name TEXT NOT NULL DEFAULT '',
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'user',
                is_active INTEGER NOT NULL DEFAULT 1,
                last_login_at TEXT,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_app_users PRIMARY KEY (id),
                CONSTRAINT uq_app_users_email UNIQUE (email)
            )
            """
        )
    else:
        op.execute(
            """
            CREATE TABLE IF NOT EXISTS app_users (
                id INTEGER CONSTRAINT pk_app_users PRIMARY KEY AUTOINCREMENT,
                email TEXT NOT NULL,
                display_name TEXT NOT NULL DEFAULT '',
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'user',
                is_active INTEGER NOT NULL DEFAULT 1,
                last_login_at TEXT,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_app_users_email UNIQUE (email)
            )
            """
        )
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_users_email ON app_users(email)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_app_users_email")
    op.execute("DROP TABLE IF EXISTS app_users")
