"""Create material catalog tables.

Revision ID: 0003_create_material_catalog
Revises: 0002_create_app_users
Create Date: 2026-05-13
"""

from __future__ import annotations

from alembic import op

revision = "0003_create_material_catalog"
down_revision = "0002_create_app_users"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _upgrade_postgresql()
        return
    _upgrade_sqlite()


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS unknown_terms")
    op.execute("DROP TABLE IF EXISTS material_aliases")
    op.execute("DROP TABLE IF EXISTS material_skus")
    op.execute("DROP TABLE IF EXISTS material_variants")
    op.execute("DROP TABLE IF EXISTS material_families")


def _upgrade_postgresql() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_families (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            code TEXT NOT NULL,
            canonical_name TEXT NOT NULL,
            category TEXT,
            default_unit TEXT NOT NULL,
            dialog_fields_json TEXT NOT NULL DEFAULT '[]',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_material_families PRIMARY KEY (id),
            CONSTRAINT uq_material_families_owner_code UNIQUE (owner_user_id, code)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_variants (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            family_id INTEGER NOT NULL REFERENCES material_families(id) ON DELETE CASCADE,
            code TEXT NOT NULL,
            display_name TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_material_variants PRIMARY KEY (id),
            CONSTRAINT uq_material_variants_owner_family_code UNIQUE (owner_user_id, family_id, code)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_skus (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            family_id INTEGER NOT NULL REFERENCES material_families(id) ON DELETE CASCADE,
            variant_id INTEGER REFERENCES material_variants(id) ON DELETE SET NULL,
            title TEXT NOT NULL,
            brand TEXT,
            supplier TEXT,
            supplier_article TEXT,
            unit TEXT NOT NULL,
            length_mm DOUBLE PRECISION,
            width_mm DOUBLE PRECISION,
            thickness_mm DOUBLE PRECISION,
            area_m2 DOUBLE PRECISION,
            extra_json TEXT,
            source_description TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_material_skus PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_aliases (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            alias TEXT NOT NULL,
            normalized_alias TEXT NOT NULL,
            family_id INTEGER REFERENCES material_families(id) ON DELETE CASCADE,
            variant_id INTEGER REFERENCES material_variants(id) ON DELETE CASCADE,
            sku_id INTEGER REFERENCES material_skus(id) ON DELETE CASCADE,
            priority INTEGER NOT NULL DEFAULT 100,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_material_aliases PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS unknown_terms (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            raw_term TEXT NOT NULL,
            normalized_term TEXT NOT NULL,
            full_message TEXT NOT NULL,
            chat_id INTEGER NOT NULL,
            message_id INTEGER,
            guessed_family_id INTEGER REFERENCES material_families(id) ON DELETE SET NULL,
            status TEXT NOT NULL DEFAULT 'new',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_unknown_terms PRIMARY KEY (id)
        )
        """
    )
    _create_indexes()


def _upgrade_sqlite() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_families (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            code TEXT NOT NULL,
            canonical_name TEXT NOT NULL,
            category TEXT,
            default_unit TEXT NOT NULL,
            dialog_fields_json TEXT NOT NULL DEFAULT '[]',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_material_families_owner_code UNIQUE (owner_user_id, code)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_variants (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            family_id INTEGER NOT NULL REFERENCES material_families(id) ON DELETE CASCADE,
            code TEXT NOT NULL,
            display_name TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_material_variants_owner_family_code UNIQUE (owner_user_id, family_id, code)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_skus (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            family_id INTEGER NOT NULL REFERENCES material_families(id) ON DELETE CASCADE,
            variant_id INTEGER REFERENCES material_variants(id) ON DELETE SET NULL,
            title TEXT NOT NULL,
            brand TEXT,
            supplier TEXT,
            supplier_article TEXT,
            unit TEXT NOT NULL,
            length_mm FLOAT,
            width_mm FLOAT,
            thickness_mm FLOAT,
            area_m2 FLOAT,
            extra_json TEXT,
            source_description TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS material_aliases (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            alias TEXT NOT NULL,
            normalized_alias TEXT NOT NULL,
            family_id INTEGER REFERENCES material_families(id) ON DELETE CASCADE,
            variant_id INTEGER REFERENCES material_variants(id) ON DELETE CASCADE,
            sku_id INTEGER REFERENCES material_skus(id) ON DELETE CASCADE,
            priority INTEGER NOT NULL DEFAULT 100,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS unknown_terms (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            raw_term TEXT NOT NULL,
            normalized_term TEXT NOT NULL,
            full_message TEXT NOT NULL,
            chat_id INTEGER NOT NULL,
            message_id INTEGER,
            guessed_family_id INTEGER REFERENCES material_families(id) ON DELETE SET NULL,
            status TEXT NOT NULL DEFAULT 'new',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    _ensure_sqlite_owner_columns()
    _create_indexes()


def _create_indexes() -> None:
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_material_families_owner_user_id ON material_families(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_material_variants_owner_user_id ON material_variants(owner_user_id)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_material_skus_owner_user_id ON material_skus(owner_user_id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_material_aliases_owner_user_id ON material_aliases(owner_user_id)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_material_aliases_normalized ON material_aliases(normalized_alias)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_unknown_terms_owner_user_id ON unknown_terms(owner_user_id)")


def _ensure_sqlite_owner_columns() -> None:
    _add_sqlite_column_if_missing(
        "material_families",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "material_variants",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "material_skus",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "material_aliases",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "unknown_terms",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )


def _add_sqlite_column_if_missing(table_name: str, column_name: str, column_sql: str) -> None:
    existing_columns = {
        str(row[1])
        for row in op.get_bind().exec_driver_sql(f"PRAGMA table_info({table_name})")
    }
    if column_name not in existing_columns:
        op.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_sql}")
