"""Create request runtime tables.

Revision ID: 0004_create_request_runtime
Revises: 0003_create_material_catalog
Create Date: 2026-05-13
"""

from __future__ import annotations

from alembic import op

revision = "0004_create_request_runtime"
down_revision = "0003_create_material_catalog"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _upgrade_postgresql()
        return
    _upgrade_sqlite()


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS telegram_notification_outbox")
    op.execute("DROP TABLE IF EXISTS group_message_history")
    op.execute("DROP TABLE IF EXISTS group_profiles")
    op.execute("DROP TABLE IF EXISTS request_items")
    op.execute("DROP TABLE IF EXISTS request_draft_participants")
    op.execute("DROP TABLE IF EXISTS request_drafts")


def _upgrade_postgresql() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS request_drafts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            master_id INTEGER NOT NULL,
            master_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'collecting',
            waiting_for TEXT,
            waiting_item_id INTEGER,
            requested_delivery_date TEXT,
            requested_delivery_time TEXT,
            confirmed_delivery_date TEXT,
            confirmed_delivery_time TEXT,
            proposed_delivery_date TEXT,
            proposed_delivery_time TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_request_drafts PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS request_draft_participants (
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            draft_id INTEGER NOT NULL REFERENCES request_drafts(id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL,
            user_name TEXT,
            role TEXT NOT NULL DEFAULT 'participant',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_request_draft_participants PRIMARY KEY (draft_id, user_id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS request_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            draft_id INTEGER NOT NULL REFERENCES request_drafts(id) ON DELETE CASCADE,
            family_id INTEGER REFERENCES material_families(id) ON DELETE SET NULL,
            variant_id INTEGER REFERENCES material_variants(id) ON DELETE SET NULL,
            sku_id INTEGER REFERENCES material_skus(id) ON DELETE SET NULL,
            raw_name TEXT NOT NULL,
            normalized_name TEXT,
            material_name_snapshot TEXT,
            unit_snapshot TEXT,
            quantity DOUBLE PRECISION,
            unit TEXT,
            thickness_mm DOUBLE PRECISION,
            length_mm DOUBLE PRECISION,
            width_mm DOUBLE PRECISION,
            note TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_request_items PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS group_profiles (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            title TEXT,
            raw_description TEXT,
            object_name TEXT,
            address TEXT,
            flat TEXT,
            floor TEXT,
            elevator TEXT,
            delivery_rules TEXT,
            delivery_start TEXT,
            delivery_end TEXT,
            delivery_fallback TEXT,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_group_profiles PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS group_message_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            user_name TEXT,
            message_id INTEGER,
            text TEXT NOT NULL,
            normalized_text TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_group_message_history PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS telegram_notification_outbox (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            text TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            attempts INTEGER NOT NULL DEFAULT 0,
            last_error TEXT,
            next_attempt_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            sent_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_telegram_notification_outbox PRIMARY KEY (id)
        )
        """
    )
    _create_indexes()


def _upgrade_sqlite() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS request_drafts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            master_id INTEGER NOT NULL,
            master_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'collecting',
            waiting_for TEXT,
            waiting_item_id INTEGER,
            requested_delivery_date TEXT,
            requested_delivery_time TEXT,
            confirmed_delivery_date TEXT,
            confirmed_delivery_time TEXT,
            proposed_delivery_date TEXT,
            proposed_delivery_time TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS request_draft_participants (
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            draft_id INTEGER NOT NULL REFERENCES request_drafts(id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL,
            user_name TEXT,
            role TEXT NOT NULL DEFAULT 'participant',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (draft_id, user_id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS request_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            draft_id INTEGER NOT NULL REFERENCES request_drafts(id) ON DELETE CASCADE,
            family_id INTEGER REFERENCES material_families(id) ON DELETE SET NULL,
            variant_id INTEGER REFERENCES material_variants(id) ON DELETE SET NULL,
            sku_id INTEGER REFERENCES material_skus(id) ON DELETE SET NULL,
            raw_name TEXT NOT NULL,
            normalized_name TEXT,
            material_name_snapshot TEXT,
            unit_snapshot TEXT,
            quantity FLOAT,
            unit TEXT,
            thickness_mm FLOAT,
            length_mm FLOAT,
            width_mm FLOAT,
            note TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS group_profiles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            title TEXT,
            raw_description TEXT,
            object_name TEXT,
            address TEXT,
            flat TEXT,
            floor TEXT,
            elevator TEXT,
            delivery_rules TEXT,
            delivery_start TEXT,
            delivery_end TEXT,
            delivery_fallback TEXT,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS group_message_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            user_name TEXT,
            message_id INTEGER,
            text TEXT NOT NULL,
            normalized_text TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS telegram_notification_outbox (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            chat_id INTEGER NOT NULL,
            text TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            attempts INTEGER NOT NULL DEFAULT 0,
            last_error TEXT,
            next_attempt_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            sent_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    _ensure_sqlite_columns()
    _create_indexes()


def _create_indexes() -> None:
    op.execute("CREATE INDEX IF NOT EXISTS ix_request_drafts_owner_user_id ON request_drafts(owner_user_id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_request_drafts_active ON request_drafts(owner_user_id, chat_id, status)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_request_items_owner_user_id ON request_items(owner_user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_request_items_draft_id ON request_items(draft_id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_request_draft_participants_user "
        "ON request_draft_participants(user_id, draft_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_group_profiles_global_chat "
        "ON group_profiles(chat_id) WHERE owner_user_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_group_profiles_owner_chat "
        "ON group_profiles(owner_user_id, chat_id) WHERE owner_user_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_group_message_history_owner_chat "
        "ON group_message_history(owner_user_id, chat_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_telegram_notification_outbox_pending "
        "ON telegram_notification_outbox(owner_user_id, status, next_attempt_at, id)"
    )


def _ensure_sqlite_columns() -> None:
    _add_sqlite_column_if_missing(
        "request_drafts",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "request_items",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing("request_items", "material_name_snapshot", "material_name_snapshot TEXT")
    _add_sqlite_column_if_missing("request_items", "unit_snapshot", "unit_snapshot TEXT")
    _add_sqlite_column_if_missing(
        "request_draft_participants",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "group_profiles",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "group_message_history",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )
    _add_sqlite_column_if_missing(
        "telegram_notification_outbox",
        "owner_user_id",
        "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
    )


def _add_sqlite_column_if_missing(table_name: str, column_name: str, column_sql: str) -> None:
    existing_columns = {
        str(row[1])
        for row in op.get_bind().exec_driver_sql(f"PRAGMA table_info({table_name})")
    }
    if column_name not in existing_columns:
        op.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_sql}")
