"""Create project workspace tables.

Revision ID: 0005_create_project_workspace
Revises: 0004_create_request_runtime
Create Date: 2026-05-13
"""

from __future__ import annotations

from alembic import op

revision = "0005_create_project_workspace"
down_revision = "0004_create_request_runtime"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _upgrade_postgresql()
        return
    _upgrade_sqlite()


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS project_contract_milestones")
    op.execute("DROP TABLE IF EXISTS project_contracts")
    op.execute("DROP TABLE IF EXISTS project_ledger_documents")
    op.execute("DROP TABLE IF EXISTS project_ledger_entries")
    op.execute("DROP TABLE IF EXISTS project_advances")
    op.execute("DROP TABLE IF EXISTS projects")


def _upgrade_postgresql() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS projects (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            code TEXT NOT NULL,
            name TEXT NOT NULL,
            address TEXT NOT NULL DEFAULT '',
            entrance_section TEXT NOT NULL DEFAULT '',
            apartment TEXT NOT NULL DEFAULT '',
            floor TEXT NOT NULL DEFAULT '',
            room_count INTEGER NOT NULL DEFAULT 0,
            has_elevator INTEGER NOT NULL DEFAULT 0,
            site_access TEXT NOT NULL DEFAULT '',
            access_hours TEXT NOT NULL DEFAULT '',
            intercom_code TEXT NOT NULL DEFAULT '',
            responsible_person TEXT NOT NULL DEFAULT '',
            comment TEXT NOT NULL DEFAULT '',
            stage_label TEXT NOT NULL DEFAULT 'Р§РµСЂРЅРѕРІРёРє',
            stage_tone TEXT NOT NULL DEFAULT 'neutral',
            estimate_project_id INTEGER,
            estimate_source TEXT NOT NULL DEFAULT '',
            area_m2 DOUBLE PRECISION NOT NULL DEFAULT 0,
            ceiling_height_m DOUBLE PRECISION NOT NULL DEFAULT 0,
            received_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            remaining_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            deferred_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            planned_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            actual_total DOUBLE PRECISION NOT NULL DEFAULT 0,
            work_per_m2 DOUBLE PRECISION NOT NULL DEFAULT 0,
            materials_per_m2 DOUBLE PRECISION NOT NULL DEFAULT 0,
            planned_margin_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
            next_delivery_label TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_projects PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_advances (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'paid',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_project_advances PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_ledger_entries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            category TEXT NOT NULL,
            item TEXT NOT NULL,
            owner TEXT NOT NULL DEFAULT '',
            counterparty TEXT NOT NULL DEFAULT '',
            counterparty_inn TEXT,
            counterparty_legal_name TEXT,
            counterparty_manager_name TEXT,
            counterparty_email TEXT,
            counterparty_phone TEXT,
            counterparty_messenger TEXT,
            status TEXT NOT NULL DEFAULT 'planned',
            plan_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            actual_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            control_date TEXT NOT NULL DEFAULT '',
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_project_ledger_entries PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_ledger_documents (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            ledger_entry_id INTEGER NOT NULL REFERENCES project_ledger_entries(id) ON DELETE CASCADE,
            kind TEXT NOT NULL,
            title TEXT NOT NULL DEFAULT '',
            date TEXT NOT NULL DEFAULT '',
            amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            source_file_name TEXT NOT NULL,
            source_mime_type TEXT NOT NULL DEFAULT 'application/octet-stream',
            source_storage_key TEXT NOT NULL,
            extracted_by_ai INTEGER NOT NULL DEFAULT 0,
            verified_by_user INTEGER NOT NULL DEFAULT 0,
            uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_project_ledger_documents PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_contracts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            file_name TEXT NOT NULL DEFAULT '',
            title TEXT NOT NULL DEFAULT '',
            number TEXT NOT NULL DEFAULT '',
            signed_at TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            planned_end_date TEXT NOT NULL DEFAULT '',
            amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            advance_terms TEXT NOT NULL DEFAULT '',
            extraction_status TEXT NOT NULL DEFAULT 'review',
            source_file_name TEXT,
            source_mime_type TEXT,
            source_storage_key TEXT,
            uploaded_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_project_contracts PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_contract_milestones (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            contract_id INTEGER NOT NULL REFERENCES project_contracts(id) ON DELETE CASCADE,
            kind TEXT NOT NULL,
            title TEXT NOT NULL,
            planned_date TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            note TEXT,
            status TEXT NOT NULL DEFAULT 'upcoming',
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT pk_project_contract_milestones PRIMARY KEY (id)
        )
        """
    )
    _create_indexes()


def _upgrade_sqlite() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS projects (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            code TEXT NOT NULL,
            name TEXT NOT NULL,
            address TEXT NOT NULL DEFAULT '',
            entrance_section TEXT NOT NULL DEFAULT '',
            apartment TEXT NOT NULL DEFAULT '',
            floor TEXT NOT NULL DEFAULT '',
            room_count INTEGER NOT NULL DEFAULT 0,
            has_elevator INTEGER NOT NULL DEFAULT 0,
            site_access TEXT NOT NULL DEFAULT '',
            access_hours TEXT NOT NULL DEFAULT '',
            intercom_code TEXT NOT NULL DEFAULT '',
            responsible_person TEXT NOT NULL DEFAULT '',
            comment TEXT NOT NULL DEFAULT '',
            stage_label TEXT NOT NULL DEFAULT 'Р§РµСЂРЅРѕРІРёРє',
            stage_tone TEXT NOT NULL DEFAULT 'neutral',
            estimate_project_id INTEGER,
            estimate_source TEXT NOT NULL DEFAULT '',
            area_m2 FLOAT NOT NULL DEFAULT 0,
            ceiling_height_m FLOAT NOT NULL DEFAULT 0,
            received_total FLOAT NOT NULL DEFAULT 0,
            remaining_total FLOAT NOT NULL DEFAULT 0,
            deferred_total FLOAT NOT NULL DEFAULT 0,
            planned_total FLOAT NOT NULL DEFAULT 0,
            actual_total FLOAT NOT NULL DEFAULT 0,
            work_per_m2 FLOAT NOT NULL DEFAULT 0,
            materials_per_m2 FLOAT NOT NULL DEFAULT 0,
            planned_margin_percent FLOAT NOT NULL DEFAULT 0,
            next_delivery_label TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_advances (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            amount FLOAT NOT NULL DEFAULT 0,
            date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'paid',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_ledger_entries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            category TEXT NOT NULL,
            item TEXT NOT NULL,
            owner TEXT NOT NULL DEFAULT '',
            counterparty TEXT NOT NULL DEFAULT '',
            counterparty_inn TEXT,
            counterparty_legal_name TEXT,
            counterparty_manager_name TEXT,
            counterparty_email TEXT,
            counterparty_phone TEXT,
            counterparty_messenger TEXT,
            status TEXT NOT NULL DEFAULT 'planned',
            plan_amount FLOAT NOT NULL DEFAULT 0,
            actual_amount FLOAT NOT NULL DEFAULT 0,
            control_date TEXT NOT NULL DEFAULT '',
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_ledger_documents (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            ledger_entry_id INTEGER NOT NULL REFERENCES project_ledger_entries(id) ON DELETE CASCADE,
            kind TEXT NOT NULL,
            title TEXT NOT NULL DEFAULT '',
            date TEXT NOT NULL DEFAULT '',
            amount FLOAT NOT NULL DEFAULT 0,
            source_file_name TEXT NOT NULL,
            source_mime_type TEXT NOT NULL DEFAULT 'application/octet-stream',
            source_storage_key TEXT NOT NULL,
            extracted_by_ai INTEGER NOT NULL DEFAULT 0,
            verified_by_user INTEGER NOT NULL DEFAULT 0,
            uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_contracts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            file_name TEXT NOT NULL DEFAULT '',
            title TEXT NOT NULL DEFAULT '',
            number TEXT NOT NULL DEFAULT '',
            signed_at TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            planned_end_date TEXT NOT NULL DEFAULT '',
            amount FLOAT NOT NULL DEFAULT 0,
            advance_terms TEXT NOT NULL DEFAULT '',
            extraction_status TEXT NOT NULL DEFAULT 'review',
            source_file_name TEXT,
            source_mime_type TEXT,
            source_storage_key TEXT,
            uploaded_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS project_contract_milestones (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            contract_id INTEGER NOT NULL REFERENCES project_contracts(id) ON DELETE CASCADE,
            kind TEXT NOT NULL,
            title TEXT NOT NULL,
            planned_date TEXT NOT NULL,
            amount FLOAT NOT NULL,
            note TEXT,
            status TEXT NOT NULL DEFAULT 'upcoming',
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    _ensure_sqlite_columns()
    _create_indexes()


def _create_indexes() -> None:
    op.execute("CREATE INDEX IF NOT EXISTS ix_projects_owner_user_id ON projects(owner_user_id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_projects_owner_updated "
        "ON projects(owner_user_id, updated_at, id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_projects_owner_estimate_project_id "
        "ON projects(owner_user_id, estimate_project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_advances_owner_project "
        "ON project_advances(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_ledger_entries_owner_project "
        "ON project_ledger_entries(owner_user_id, project_id, sort_order, id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_project_ledger_documents_global_entry_kind "
        "ON project_ledger_documents(ledger_entry_id, kind) WHERE owner_user_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_project_ledger_documents_owner_entry_kind "
        "ON project_ledger_documents(owner_user_id, ledger_entry_id, kind) WHERE owner_user_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_ledger_documents_owner_project "
        "ON project_ledger_documents(owner_user_id, project_id, ledger_entry_id, kind)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_project_contracts_global_project "
        "ON project_contracts(project_id) WHERE owner_user_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_project_contracts_owner_project "
        "ON project_contracts(owner_user_id, project_id) WHERE owner_user_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_contract_milestones_owner_contract "
        "ON project_contract_milestones(owner_user_id, contract_id, sort_order, id)"
    )


def _ensure_sqlite_columns() -> None:
    for table_name in (
        "projects",
        "project_advances",
        "project_ledger_entries",
        "project_ledger_documents",
        "project_contracts",
        "project_contract_milestones",
    ):
        _add_sqlite_column_if_missing(
            table_name,
            "owner_user_id",
            "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
        )


def _add_sqlite_column_if_missing(table_name: str, column_name: str, column_sql: str) -> None:
    existing_columns = {
        str(row[1])
        for row in op.get_bind().exec_driver_sql(f"PRAGMA table_info({table_name})")
    }
    if column_name not in existing_columns:
        op.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_sql}")



