"""Создать schema foundation для calculator/estimates.

Revision ID: 0006_create_estimate_calculator
Revises: 0005_create_project_workspace
Create Date: 2026-05-13
"""

from __future__ import annotations

from alembic import op

revision = "0006_create_estimate_calculator"
down_revision = "0005_create_project_workspace"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _create_tables(
            id_sql="INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            float_sql="DOUBLE PRECISION",
        )
        _create_indexes()
        return
    _create_tables(id_sql="INTEGER PRIMARY KEY AUTOINCREMENT", float_sql="FLOAT")
    _ensure_sqlite_columns()
    _create_indexes()


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS estimate_project_door_components")
    op.execute("DROP TABLE IF EXISTS estimate_project_doors")
    op.execute("DROP TABLE IF EXISTS estimate_door_component_catalog")
    op.execute("DROP TABLE IF EXISTS estimate_door_catalog")
    op.execute("DROP TABLE IF EXISTS estimate_wall_finish_room_zones")
    op.execute("DROP TABLE IF EXISTS estimate_wall_finish_rooms")
    op.execute("DROP TABLE IF EXISTS estimate_wall_finish_configs")
    op.execute("DROP TABLE IF EXISTS estimate_wall_finish_layouts")
    op.execute("DROP TABLE IF EXISTS estimate_wall_finish_preparations")
    op.execute("DROP TABLE IF EXISTS estimate_wall_finish_coverings")
    op.execute("DROP TABLE IF EXISTS estimate_flooring_room_zones")
    op.execute("DROP TABLE IF EXISTS estimate_flooring_rooms")
    op.execute("DROP TABLE IF EXISTS estimate_flooring_configs")
    op.execute("DROP TABLE IF EXISTS estimate_flooring_layouts")
    op.execute("DROP TABLE IF EXISTS estimate_flooring_preparations")
    op.execute("DROP TABLE IF EXISTS estimate_flooring_coverings")
    op.execute("DROP TABLE IF EXISTS estimate_warm_floor_rooms")
    op.execute("DROP TABLE IF EXISTS estimate_warm_floor_configs")
    op.execute("DROP TABLE IF EXISTS estimate_room_openings")
    op.execute("DROP TABLE IF EXISTS estimate_room_floor_sections")
    op.execute("DROP TABLE IF EXISTS estimate_room_walls")
    op.execute("DROP TABLE IF EXISTS estimate_rooms")
    op.execute("DROP TABLE IF EXISTS estimate_projects")


def _create_tables(*, id_sql: str, float_sql: str) -> None:
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_projects (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            residential_complex TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '',
            entrance_section TEXT NOT NULL DEFAULT '',
            apartment TEXT NOT NULL DEFAULT '',
            floor TEXT NOT NULL DEFAULT '',
            has_elevator INTEGER NOT NULL DEFAULT 0,
            lift_type TEXT NOT NULL DEFAULT '',
            site_access TEXT NOT NULL DEFAULT '',
            intercom_code TEXT NOT NULL DEFAULT '',
            loading_zone TEXT NOT NULL DEFAULT '',
            responsible_person TEXT NOT NULL DEFAULT '',
            note TEXT,
            group_chat_id INTEGER,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_rooms (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            ceiling_height_m {float_sql} NOT NULL DEFAULT 2.7,
            manual_floor_area_m2 {float_sql},
            auto_perimeter_calc INTEGER NOT NULL DEFAULT 0,
            perimeter_factor {float_sql} NOT NULL DEFAULT 1.15,
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_room_walls (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            length_m {float_sql} NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 100
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_room_floor_sections (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            length_m {float_sql} NOT NULL,
            width_m {float_sql} NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 100
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_room_openings (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            opening_type TEXT NOT NULL DEFAULT 'window',
            width_m {float_sql},
            height_m {float_sql},
            quantity {float_sql} NOT NULL DEFAULT 1,
            area_m2 {float_sql},
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_warm_floor_configs (
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER PRIMARY KEY REFERENCES estimate_projects(id) ON DELETE CASCADE,
            work_price_per_m2 {float_sql} NOT NULL DEFAULT 1600,
            pipe_m_per_m2 {float_sql} NOT NULL DEFAULT 6,
            max_contour_area_m2 {float_sql} NOT NULL DEFAULT 15,
            small_zone_area_m2 {float_sql} NOT NULL DEFAULT 5,
            manifold_work_price {float_sql} NOT NULL DEFAULT 6000,
            manifold_material_price {float_sql} NOT NULL DEFAULT 20000,
            pump_work_price {float_sql} NOT NULL DEFAULT 8000,
            pump_material_price {float_sql} NOT NULL DEFAULT 25000,
            pipe_price_per_m {float_sql} NOT NULL DEFAULT 170,
            pipe_material_title TEXT NOT NULL DEFAULT 'Труба PEX-a 16x2 для водяного теплого пола',
            manifold_material_items_json TEXT NOT NULL DEFAULT '',
            pump_material_items_json TEXT NOT NULL DEFAULT '',
            consumable_material_items_json TEXT NOT NULL DEFAULT '',
            pump_rooms_threshold INTEGER NOT NULL DEFAULT 3,
            pump_contours_threshold INTEGER NOT NULL DEFAULT 4,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_warm_floor_rooms (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            area_m2_override {float_sql},
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_coverings (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            material_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            labor_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            base_waste_percent {float_sql} NOT NULL DEFAULT 0,
            underlay_mode TEXT NOT NULL DEFAULT 'none',
            underlay_consumption_per_m2 {float_sql} NOT NULL DEFAULT 1,
            glue_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            glue_unit TEXT NOT NULL DEFAULT 'кг',
            glue_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            primer_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            primer_unit TEXT NOT NULL DEFAULT 'л',
            primer_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            svp_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            svp_unit TEXT NOT NULL DEFAULT 'шт',
            svp_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            grout_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            grout_unit TEXT NOT NULL DEFAULT 'кг',
            grout_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            needs_plinth INTEGER NOT NULL DEFAULT 1,
            instrument_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            custom_consumables_json TEXT NOT NULL DEFAULT '',
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_preparations (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            labor_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            material_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            primer_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            primer_unit TEXT NOT NULL DEFAULT 'л',
            primer_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_layouts (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            labor_multiplier {float_sql} NOT NULL DEFAULT 1,
            extra_waste_percent {float_sql} NOT NULL DEFAULT 0,
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_configs (
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER PRIMARY KEY REFERENCES estimate_projects(id) ON DELETE CASCADE,
            default_preparation_id INTEGER REFERENCES estimate_flooring_preparations(id) ON DELETE SET NULL,
            include_underlay INTEGER NOT NULL DEFAULT 1,
            include_plinth INTEGER NOT NULL DEFAULT 1,
            include_demolition INTEGER NOT NULL DEFAULT 0,
            include_preparation INTEGER NOT NULL DEFAULT 1,
            demolition_price_per_m2 {float_sql} NOT NULL DEFAULT 150,
            underlay_price_per_m2 {float_sql} NOT NULL DEFAULT 120,
            plinth_material_price_per_m {float_sql} NOT NULL DEFAULT 180,
            plinth_install_price_per_m {float_sql} NOT NULL DEFAULT 250,
            threshold_profile_count INTEGER NOT NULL DEFAULT 0,
            threshold_profile_price {float_sql} NOT NULL DEFAULT 900,
            global_items_json TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_rooms (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            covering_id INTEGER REFERENCES estimate_flooring_coverings(id) ON DELETE SET NULL,
            preparation_id INTEGER REFERENCES estimate_flooring_preparations(id) ON DELETE SET NULL,
            layout_id INTEGER REFERENCES estimate_flooring_layouts(id) ON DELETE SET NULL,
            area_m2_override {float_sql},
            perimeter_m_override {float_sql},
            plinth_m_override {float_sql},
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_room_zones (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            covering_id INTEGER REFERENCES estimate_flooring_coverings(id) ON DELETE SET NULL,
            preparation_id INTEGER REFERENCES estimate_flooring_preparations(id) ON DELETE SET NULL,
            layout_id INTEGER REFERENCES estimate_flooring_layouts(id) ON DELETE SET NULL,
            area_m2 {float_sql},
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_wall_finish_coverings (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            material_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            labor_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            base_waste_percent {float_sql} NOT NULL DEFAULT 0,
            glue_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            glue_unit TEXT NOT NULL DEFAULT 'кг',
            glue_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            primer_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            primer_unit TEXT NOT NULL DEFAULT 'л',
            primer_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            putty_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            putty_unit TEXT NOT NULL DEFAULT 'кг',
            putty_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            mesh_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            mesh_unit TEXT NOT NULL DEFAULT 'м2',
            mesh_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            custom_consumables_json TEXT NOT NULL DEFAULT '',
            instrument_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_wall_finish_preparations (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            labor_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            material_price_per_m2 {float_sql} NOT NULL DEFAULT 0,
            primer_consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            primer_unit TEXT NOT NULL DEFAULT 'л',
            primer_price_per_unit {float_sql} NOT NULL DEFAULT 0,
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_wall_finish_layouts (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            labor_multiplier {float_sql} NOT NULL DEFAULT 1,
            extra_waste_percent {float_sql} NOT NULL DEFAULT 0,
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_wall_finish_configs (
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER PRIMARY KEY REFERENCES estimate_projects(id) ON DELETE CASCADE,
            include_preparation INTEGER NOT NULL DEFAULT 1,
            include_demolition INTEGER NOT NULL DEFAULT 0,
            demolition_price_per_m2 {float_sql} NOT NULL DEFAULT 140,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_wall_finish_rooms (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            covering_id INTEGER REFERENCES estimate_wall_finish_coverings(id) ON DELETE SET NULL,
            preparation_id INTEGER REFERENCES estimate_wall_finish_preparations(id) ON DELETE SET NULL,
            layout_id INTEGER REFERENCES estimate_wall_finish_layouts(id) ON DELETE SET NULL,
            area_m2_override {float_sql},
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_wall_finish_room_zones (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            covering_id INTEGER REFERENCES estimate_wall_finish_coverings(id) ON DELETE SET NULL,
            preparation_id INTEGER REFERENCES estimate_wall_finish_preparations(id) ON DELETE SET NULL,
            layout_id INTEGER REFERENCES estimate_wall_finish_layouts(id) ON DELETE SET NULL,
            area_m2 {float_sql},
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_door_catalog (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            width_mm {float_sql} NOT NULL,
            height_mm {float_sql} NOT NULL,
            thickness_mm {float_sql},
            area_m2 {float_sql},
            purchase_price {float_sql},
            sale_price {float_sql},
            install_price {float_sql},
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_project_doors (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            door_catalog_id INTEGER REFERENCES estimate_door_catalog(id) ON DELETE SET NULL,
            title TEXT,
            opening_kind TEXT NOT NULL DEFAULT 'door',
            width_mm {float_sql},
            height_mm {float_sql},
            thickness_mm {float_sql},
            area_m2 {float_sql},
            purchase_price {float_sql},
            sale_price {float_sql},
            install_price {float_sql},
            room_a_id INTEGER REFERENCES estimate_rooms(id) ON DELETE SET NULL,
            room_b_id INTEGER REFERENCES estimate_rooms(id) ON DELETE SET NULL,
            note TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_door_component_catalog (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            category_code TEXT NOT NULL,
            title TEXT NOT NULL,
            unit TEXT NOT NULL DEFAULT 'шт',
            purchase_price {float_sql},
            sale_price {float_sql},
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_project_door_components (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_door_id INTEGER NOT NULL REFERENCES estimate_project_doors(id) ON DELETE CASCADE,
            component_catalog_id INTEGER REFERENCES estimate_door_component_catalog(id) ON DELETE SET NULL,
            category_code TEXT NOT NULL,
            title TEXT NOT NULL,
            unit TEXT NOT NULL DEFAULT 'шт',
            quantity {float_sql} NOT NULL DEFAULT 1,
            purchase_price {float_sql},
            sale_price {float_sql},
            note TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def _create_indexes() -> None:
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_projects_owner_updated "
        "ON estimate_projects(owner_user_id, updated_at, id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_projects_owner_group_chat "
        "ON estimate_projects(owner_user_id, group_chat_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_rooms_owner_project "
        "ON estimate_rooms(owner_user_id, project_id, sort_order)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_room_walls_owner_room "
        "ON estimate_room_walls(owner_user_id, room_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_room_floor_sections_owner_room "
        "ON estimate_room_floor_sections(owner_user_id, room_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_room_openings_owner_room "
        "ON estimate_room_openings(owner_user_id, room_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_warm_floor_rooms_owner_project "
        "ON estimate_warm_floor_rooms(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_warm_floor_rooms_global_project_room "
        "ON estimate_warm_floor_rooms(project_id, room_id) WHERE owner_user_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_warm_floor_rooms_owner_project_room "
        "ON estimate_warm_floor_rooms(owner_user_id, project_id, room_id) WHERE owner_user_id IS NOT NULL"
    )
    _create_catalog_unique_indexes(
        table_name="estimate_flooring_coverings",
        global_index="uq_estimate_flooring_coverings_global_title",
        owner_index="uq_estimate_flooring_coverings_owner_title",
    )
    _create_catalog_unique_indexes(
        table_name="estimate_flooring_preparations",
        global_index="uq_estimate_flooring_preparations_global_title",
        owner_index="uq_estimate_flooring_preparations_owner_title",
    )
    _create_catalog_unique_indexes(
        table_name="estimate_flooring_layouts",
        global_index="uq_estimate_flooring_layouts_global_title",
        owner_index="uq_estimate_flooring_layouts_owner_title",
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_rooms_owner_project "
        "ON estimate_flooring_rooms(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_flooring_rooms_global_project_room "
        "ON estimate_flooring_rooms(project_id, room_id) WHERE owner_user_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_flooring_rooms_owner_project_room "
        "ON estimate_flooring_rooms(owner_user_id, project_id, room_id) WHERE owner_user_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_room_zones_owner_project_room "
        "ON estimate_flooring_room_zones(owner_user_id, project_id, room_id)"
    )
    _create_catalog_unique_indexes(
        table_name="estimate_wall_finish_coverings",
        global_index="uq_estimate_wall_finish_coverings_global_title",
        owner_index="uq_estimate_wall_finish_coverings_owner_title",
    )
    _create_catalog_unique_indexes(
        table_name="estimate_wall_finish_preparations",
        global_index="uq_estimate_wall_finish_preparations_global_title",
        owner_index="uq_estimate_wall_finish_preparations_owner_title",
    )
    _create_catalog_unique_indexes(
        table_name="estimate_wall_finish_layouts",
        global_index="uq_estimate_wall_finish_layouts_global_title",
        owner_index="uq_estimate_wall_finish_layouts_owner_title",
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_wall_finish_rooms_owner_project "
        "ON estimate_wall_finish_rooms(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_wall_finish_rooms_global_project_room "
        "ON estimate_wall_finish_rooms(project_id, room_id) WHERE owner_user_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_wall_finish_rooms_owner_project_room "
        "ON estimate_wall_finish_rooms(owner_user_id, project_id, room_id) WHERE owner_user_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_wall_finish_room_zones_owner_project_room "
        "ON estimate_wall_finish_room_zones(owner_user_id, project_id, room_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_door_catalog_owner_active "
        "ON estimate_door_catalog(owner_user_id, is_active)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_door_component_catalog_owner_category "
        "ON estimate_door_component_catalog(owner_user_id, category_code)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_doors_owner_project "
        "ON estimate_project_doors(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_door_components_owner_project_door "
        "ON estimate_project_door_components(owner_user_id, project_door_id)"
    )


def _create_catalog_unique_indexes(*, table_name: str, global_index: str, owner_index: str) -> None:
    op.execute(
        f"CREATE UNIQUE INDEX IF NOT EXISTS {global_index} "
        f"ON {table_name}(title) WHERE owner_user_id IS NULL"
    )
    op.execute(
        f"CREATE UNIQUE INDEX IF NOT EXISTS {owner_index} "
        f"ON {table_name}(owner_user_id, title) WHERE owner_user_id IS NOT NULL"
    )


def _ensure_sqlite_columns() -> None:
    for table_name in (
        "estimate_projects",
        "estimate_rooms",
        "estimate_room_walls",
        "estimate_room_floor_sections",
        "estimate_room_openings",
        "estimate_warm_floor_configs",
        "estimate_warm_floor_rooms",
        "estimate_flooring_coverings",
        "estimate_flooring_preparations",
        "estimate_flooring_layouts",
        "estimate_flooring_configs",
        "estimate_flooring_rooms",
        "estimate_flooring_room_zones",
        "estimate_wall_finish_coverings",
        "estimate_wall_finish_preparations",
        "estimate_wall_finish_layouts",
        "estimate_wall_finish_configs",
        "estimate_wall_finish_rooms",
        "estimate_wall_finish_room_zones",
        "estimate_door_catalog",
        "estimate_project_doors",
        "estimate_door_component_catalog",
        "estimate_project_door_components",
    ):
        _add_sqlite_column_if_missing(
            table_name,
            "owner_user_id",
            "owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE",
        )


def _add_sqlite_column_if_missing(table_name: str, column_name: str, column_sql: str) -> None:
    existing_columns = {
        str(row[1])
        for row in op.get_bind().exec_driver_sql(f"PRAGMA table_info({table_name})")
    }
    if column_name not in existing_columns:
        op.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_sql}")
