"""Создать таблицы потолочного калькулятора.

Revision ID: 0007_create_estimate_ceilings
Revises: 0006_create_estimate_calculator
Create Date: 2026-05-14
"""

from alembic import op

revision = "0007_create_estimate_ceilings"
down_revision = "0006_create_estimate_calculator"
branch_labels = None
depends_on = None


def _dialect_name() -> str:
    return op.get_bind().dialect.name


def _identity_sql() -> str:
    if _dialect_name() == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def _float_sql() -> str:
    if _dialect_name() == "postgresql":
        return "DOUBLE PRECISION"
    return "FLOAT"


def _create_tables() -> None:
    id_sql = _identity_sql()
    float_sql = _float_sql()

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_ceiling_configs (
            project_id INTEGER PRIMARY KEY REFERENCES estimate_projects(id) ON DELETE CASCADE,
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            default_package_code TEXT,
            price_factor {float_sql} NOT NULL DEFAULT 1,
            note TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_ceiling_catalog_items (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            source_code TEXT NOT NULL,
            title TEXT NOT NULL,
            category TEXT NOT NULL,
            unit TEXT NOT NULL,
            work_price {float_sql} NOT NULL DEFAULT 0,
            material_price {float_sql} NOT NULL DEFAULT 0,
            equipment_price {float_sql} NOT NULL DEFAULT 0,
            consumables_price {float_sql} NOT NULL DEFAULT 0,
            price_factor {float_sql} NOT NULL DEFAULT 1,
            quantity_source TEXT,
            quantity_formula TEXT,
            include_section TEXT NOT NULL DEFAULT 'ceilings',
            package_code TEXT,
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_ceiling_rooms (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            room_id INTEGER NOT NULL REFERENCES estimate_rooms(id) ON DELETE CASCADE,
            default_catalog_item_id INTEGER REFERENCES estimate_ceiling_catalog_items(id) ON DELETE SET NULL,
            is_enabled INTEGER NOT NULL DEFAULT 1,
            ceiling_area_m2 {float_sql},
            area_source TEXT NOT NULL DEFAULT 'room_area',
            perimeter_m {float_sql},
            perimeter_source TEXT NOT NULL DEFAULT 'room_perimeter',
            package_code_snapshot TEXT,
            note TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_project_ceiling_items (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            project_id INTEGER NOT NULL REFERENCES estimate_projects(id) ON DELETE CASCADE,
            room_id INTEGER REFERENCES estimate_rooms(id) ON DELETE SET NULL,
            source_catalog_item_id INTEGER REFERENCES estimate_ceiling_catalog_items(id) ON DELETE SET NULL,
            source_code_snapshot TEXT,
            title_snapshot TEXT NOT NULL,
            category_snapshot TEXT,
            unit_snapshot TEXT NOT NULL,
            quantity {float_sql} NOT NULL DEFAULT 0,
            quantity_source TEXT NOT NULL DEFAULT 'manual',
            quantity_formula_snapshot TEXT,
            work_price_snapshot {float_sql} NOT NULL DEFAULT 0,
            material_price_snapshot {float_sql} NOT NULL DEFAULT 0,
            equipment_price_snapshot {float_sql} NOT NULL DEFAULT 0,
            consumables_price_snapshot {float_sql} NOT NULL DEFAULT 0,
            price_factor_snapshot {float_sql} NOT NULL DEFAULT 1,
            work_total {float_sql} NOT NULL DEFAULT 0,
            material_total {float_sql} NOT NULL DEFAULT 0,
            equipment_total {float_sql} NOT NULL DEFAULT 0,
            consumables_total {float_sql} NOT NULL DEFAULT 0,
            total {float_sql} NOT NULL DEFAULT 0,
            note_snapshot TEXT,
            is_enabled INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def _create_indexes() -> None:
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_configs_owner "
        "ON estimate_ceiling_configs(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_configs_project "
        "ON estimate_ceiling_configs(project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_configs_owner_project "
        "ON estimate_ceiling_configs(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_catalog_items_owner "
        "ON estimate_ceiling_catalog_items(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_catalog_items_source_code "
        "ON estimate_ceiling_catalog_items(source_code)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_catalog_items_owner_active "
        "ON estimate_ceiling_catalog_items(owner_user_id, is_active)"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_ceiling_catalog_items_global_source_code
        ON estimate_ceiling_catalog_items(source_code)
        WHERE owner_user_id IS NULL
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_ceiling_catalog_items_owner_source_code
        ON estimate_ceiling_catalog_items(owner_user_id, source_code)
        WHERE owner_user_id IS NOT NULL
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_rooms_owner "
        "ON estimate_ceiling_rooms(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_rooms_project "
        "ON estimate_ceiling_rooms(project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_rooms_room "
        "ON estimate_ceiling_rooms(room_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_rooms_owner_project "
        "ON estimate_ceiling_rooms(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_ceiling_rooms_owner_project_room "
        "ON estimate_ceiling_rooms(owner_user_id, project_id, room_id)"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_ceiling_rooms_global_project_room
        ON estimate_ceiling_rooms(project_id, room_id)
        WHERE owner_user_id IS NULL
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_ceiling_rooms_owner_project_room
        ON estimate_ceiling_rooms(owner_user_id, project_id, room_id)
        WHERE owner_user_id IS NOT NULL
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_ceiling_items_owner "
        "ON estimate_project_ceiling_items(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_ceiling_items_project "
        "ON estimate_project_ceiling_items(project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_ceiling_items_room "
        "ON estimate_project_ceiling_items(room_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_ceiling_items_source_catalog "
        "ON estimate_project_ceiling_items(source_catalog_item_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_ceiling_items_owner_project "
        "ON estimate_project_ceiling_items(owner_user_id, project_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_project_ceiling_items_owner_project_room "
        "ON estimate_project_ceiling_items(owner_user_id, project_id, room_id)"
    )


def upgrade() -> None:
    _create_tables()
    _create_indexes()


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS estimate_project_ceiling_items")
    op.execute("DROP TABLE IF EXISTS estimate_ceiling_rooms")
    op.execute("DROP TABLE IF EXISTS estimate_ceiling_catalog_items")
    op.execute("DROP TABLE IF EXISTS estimate_ceiling_configs")
