"""Create public leads table.

Revision ID: 0010_create_public_leads
Revises: 0009_use_bigint_for_telegram_ids
Create Date: 2026-05-24
"""

from __future__ import annotations

from alembic import op

revision = "0010_create_public_leads"
down_revision = "0009_use_bigint_for_telegram_ids"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _upgrade_postgresql()
        return
    _upgrade_sqlite()


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS public_leads")


def _upgrade_postgresql() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public_leads (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            name TEXT NOT NULL,
            contact TEXT NOT NULL,
            contact_method TEXT NOT NULL DEFAULT '',
            object_type TEXT NOT NULL DEFAULT '',
            area TEXT NOT NULL DEFAULT '',
            package_type TEXT NOT NULL DEFAULT '',
            comment TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT 'public_landing',
            status TEXT NOT NULL DEFAULT 'new',
            personal_data_consent BOOLEAN NOT NULL DEFAULT TRUE,
            telegram_delivery_status TEXT NOT NULL DEFAULT 'not_sent',
            telegram_message_id INTEGER,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed_by INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
            reviewed_at TEXT,
            CONSTRAINT pk_public_leads PRIMARY KEY (id)
        )
        """
    )
    _create_indexes()


def _upgrade_sqlite() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public_leads (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            contact TEXT NOT NULL,
            contact_method TEXT NOT NULL DEFAULT '',
            object_type TEXT NOT NULL DEFAULT '',
            area TEXT NOT NULL DEFAULT '',
            package_type TEXT NOT NULL DEFAULT '',
            comment TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT 'public_landing',
            status TEXT NOT NULL DEFAULT 'new',
            personal_data_consent INTEGER NOT NULL DEFAULT 1,
            telegram_delivery_status TEXT NOT NULL DEFAULT 'not_sent',
            telegram_message_id INTEGER,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed_by INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
            reviewed_at TEXT
        )
        """
    )
    _create_indexes()


def _create_indexes() -> None:
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_public_leads_status_created_at "
        "ON public_leads(status, created_at, id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_public_leads_created_at "
        "ON public_leads(created_at, id)"
    )
