"""Создать таблицы каталога сантехники (Трек A, этап A1).

Revision ID: 0011_create_estimate_plumbing
Revises: 0010_create_public_leads
Create Date: 2026-05-29
"""

from alembic import op

revision = "0011_create_estimate_plumbing"
down_revision = "0010_create_public_leads"
branch_labels = None
depends_on = None


def _dialect_name() -> str:
    return op.get_bind().dialect.name


def _identity_sql() -> str:
    if _dialect_name() == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def _float_sql() -> str:
    if _dialect_name() == "postgresql":
        return "DOUBLE PRECISION"
    return "FLOAT"


def _create_tables() -> None:
    id_sql = _identity_sql()
    float_sql = _float_sql()

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_plumbing_catalog_items (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            source_code TEXT NOT NULL,
            public_title TEXT NOT NULL,
            technical_title TEXT,
            category TEXT NOT NULL,
            unit TEXT NOT NULL,
            work_price {float_sql} NOT NULL DEFAULT 0,
            material_price {float_sql} NOT NULL DEFAULT 0,
            equipment_price {float_sql} NOT NULL DEFAULT 0,
            consumables_price {float_sql} NOT NULL DEFAULT 0,
            coefficient {float_sql} NOT NULL DEFAULT 1,
            catalog_group TEXT,
            source TEXT,
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_plumbing_zones (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            zone_code TEXT NOT NULL,
            subgroup TEXT NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            disclaimer TEXT,
            risk_percent {float_sql} NOT NULL DEFAULT 6.4,
            active_package_code TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_plumbing_zone_items (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            zone_id INTEGER NOT NULL REFERENCES estimate_plumbing_zones(id) ON DELETE CASCADE,
            atomic_item_id INTEGER REFERENCES estimate_plumbing_catalog_items(id) ON DELETE SET NULL,
            atomic_source_code TEXT NOT NULL,
            quantity {float_sql} NOT NULL DEFAULT 0,
            coefficient {float_sql} NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_plumbing_zone_packages (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            zone_id INTEGER NOT NULL REFERENCES estimate_plumbing_zones(id) ON DELETE CASCADE,
            package_code TEXT NOT NULL,
            label TEXT,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_plumbing_zone_package_items (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            package_id INTEGER NOT NULL REFERENCES estimate_plumbing_zone_packages(id) ON DELETE CASCADE,
            zone_id INTEGER NOT NULL REFERENCES estimate_plumbing_zones(id) ON DELETE CASCADE,
            atomic_item_id INTEGER REFERENCES estimate_plumbing_catalog_items(id) ON DELETE SET NULL,
            atomic_source_code TEXT NOT NULL,
            quantity {float_sql} NOT NULL DEFAULT 0,
            coefficient {float_sql} NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_plumbing_catalog_audit (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            entity_type TEXT NOT NULL,
            entity_id INTEGER,
            action TEXT NOT NULL,
            changed_by_user_id INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
            diff_json TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def _create_indexes() -> None:
    # catalog items
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_catalog_items_owner "
        "ON estimate_plumbing_catalog_items(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_catalog_items_source_code "
        "ON estimate_plumbing_catalog_items(source_code)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_catalog_items_owner_active "
        "ON estimate_plumbing_catalog_items(owner_user_id, is_active)"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_plumbing_catalog_items_global_source_code
        ON estimate_plumbing_catalog_items(source_code)
        WHERE owner_user_id IS NULL
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_plumbing_catalog_items_owner_source_code
        ON estimate_plumbing_catalog_items(owner_user_id, source_code)
        WHERE owner_user_id IS NOT NULL
        """
    )
    # zones
    op.execute("CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zones_owner ON estimate_plumbing_zones(owner_user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zones_zone_code ON estimate_plumbing_zones(zone_code)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zones_owner_active "
        "ON estimate_plumbing_zones(owner_user_id, is_active)"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_plumbing_zones_global_zone_code
        ON estimate_plumbing_zones(zone_code)
        WHERE owner_user_id IS NULL
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_plumbing_zones_owner_zone_code
        ON estimate_plumbing_zones(owner_user_id, zone_code)
        WHERE owner_user_id IS NOT NULL
        """
    )
    # zone items
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_items_owner "
        "ON estimate_plumbing_zone_items(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_items_zone ON estimate_plumbing_zone_items(zone_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_items_atomic "
        "ON estimate_plumbing_zone_items(atomic_item_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_items_atomic_source_code "
        "ON estimate_plumbing_zone_items(atomic_source_code)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_items_owner_zone "
        "ON estimate_plumbing_zone_items(owner_user_id, zone_id)"
    )
    # zone packages
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_packages_owner "
        "ON estimate_plumbing_zone_packages(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_packages_zone ON estimate_plumbing_zone_packages(zone_id)"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_plumbing_zone_packages_zone_code
        ON estimate_plumbing_zone_packages(zone_id, package_code)
        """
    )
    # zone package items
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_package_items_owner "
        "ON estimate_plumbing_zone_package_items(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_package_items_package "
        "ON estimate_plumbing_zone_package_items(package_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_package_items_zone "
        "ON estimate_plumbing_zone_package_items(zone_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_package_items_atomic "
        "ON estimate_plumbing_zone_package_items(atomic_item_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_zone_package_items_atomic_source_code "
        "ON estimate_plumbing_zone_package_items(atomic_source_code)"
    )
    # audit
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_catalog_audit_entity "
        "ON estimate_plumbing_catalog_audit(entity_type, entity_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_catalog_audit_changed_by "
        "ON estimate_plumbing_catalog_audit(changed_by_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_plumbing_catalog_audit_created_at "
        "ON estimate_plumbing_catalog_audit(created_at)"
    )


def upgrade() -> None:
    _create_tables()
    _create_indexes()


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS estimate_plumbing_catalog_audit")
    op.execute("DROP TABLE IF EXISTS estimate_plumbing_zone_package_items")
    op.execute("DROP TABLE IF EXISTS estimate_plumbing_zone_packages")
    op.execute("DROP TABLE IF EXISTS estimate_plumbing_zone_items")
    op.execute("DROP TABLE IF EXISTS estimate_plumbing_zones")
    op.execute("DROP TABLE IF EXISTS estimate_plumbing_catalog_items")
