"""Create flooring assembly item catalog.

Revision ID: 0012_create_flooring_assembly_items
Revises: 0011_create_estimate_plumbing
Create Date: 2026-06-01
"""

from alembic import op

revision = "0012_create_flooring_assembly_items"
down_revision = "0011_create_estimate_plumbing"
branch_labels = None
depends_on = None


def _dialect_name() -> str:
    return op.get_bind().dialect.name


def _identity_sql() -> str:
    if _dialect_name() == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def _float_sql() -> str:
    if _dialect_name() == "postgresql":
        return "DOUBLE PRECISION"
    return "FLOAT"


def upgrade() -> None:
    id_sql = _identity_sql()
    float_sql = _float_sql()
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_assembly_items (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            source_code TEXT NOT NULL,
            section TEXT NOT NULL,
            title TEXT NOT NULL,
            kind TEXT NOT NULL,
            formula TEXT NOT NULL,
            unit TEXT NOT NULL DEFAULT 'pcs',
            price {float_sql} NOT NULL DEFAULT 0,
            consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            package_size {float_sql},
            layer_mm {float_sql},
            note TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_assembly_items_owner "
        "ON estimate_flooring_assembly_items(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_assembly_items_section "
        "ON estimate_flooring_assembly_items(section)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_assembly_items_owner_active "
        "ON estimate_flooring_assembly_items(owner_user_id, is_active)"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_flooring_assembly_items_global_code
        ON estimate_flooring_assembly_items(source_code)
        WHERE owner_user_id IS NULL
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_flooring_assembly_items_owner_code
        ON estimate_flooring_assembly_items(owner_user_id, source_code)
        WHERE owner_user_id IS NOT NULL
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS estimate_flooring_assembly_items")
