"""Create flooring catalog assembly tables.

Revision ID: 0013_flooring_catalog_assemblies
Revises: 0012_flooring_assembly_items
Create Date: 2026-06-02
"""

from alembic import op

revision = "0013_flooring_catalog_assemblies"
down_revision = "0012_flooring_assembly_items"
branch_labels = None
depends_on = None


def _dialect_name() -> str:
    return op.get_bind().dialect.name


def _identity_sql() -> str:
    if _dialect_name() == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def _float_sql() -> str:
    if _dialect_name() == "postgresql":
        return "DOUBLE PRECISION"
    return "FLOAT"


def upgrade() -> None:
    id_sql = _identity_sql()
    float_sql = _float_sql()
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_catalog_assemblies (
            id {id_sql},
            owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
            target_kind TEXT NOT NULL,
            target_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            version TEXT NOT NULL DEFAULT 'flooring-assembly-v1',
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_catalog_assemblies_owner "
        "ON estimate_flooring_catalog_assemblies(owner_user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_catalog_assemblies_target "
        "ON estimate_flooring_catalog_assemblies(target_kind, target_id)"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_flooring_catalog_assemblies_global_target
        ON estimate_flooring_catalog_assemblies(target_kind, target_id)
        WHERE owner_user_id IS NULL
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_estimate_flooring_catalog_assemblies_owner_target
        ON estimate_flooring_catalog_assemblies(owner_user_id, target_kind, target_id)
        WHERE owner_user_id IS NOT NULL
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS estimate_flooring_catalog_assembly_rows (
            id {id_sql},
            assembly_id INTEGER NOT NULL REFERENCES estimate_flooring_catalog_assemblies(id) ON DELETE CASCADE,
            assembly_item_id INTEGER REFERENCES estimate_flooring_assembly_items(id) ON DELETE SET NULL,
            section TEXT NOT NULL,
            kind TEXT NOT NULL,
            formula TEXT NOT NULL,
            title TEXT NOT NULL,
            unit TEXT NOT NULL DEFAULT 'pcs',
            price {float_sql} NOT NULL DEFAULT 0,
            consumption_per_m2 {float_sql} NOT NULL DEFAULT 0,
            package_size {float_sql},
            layer_mm {float_sql},
            sort_order INTEGER NOT NULL DEFAULT 100,
            is_enabled INTEGER NOT NULL DEFAULT 1,
            public_category TEXT NOT NULL,
            public_title TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_catalog_assembly_rows_assembly "
        "ON estimate_flooring_catalog_assembly_rows(assembly_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_catalog_assembly_rows_item "
        "ON estimate_flooring_catalog_assembly_rows(assembly_item_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_estimate_flooring_catalog_assembly_rows_sort "
        "ON estimate_flooring_catalog_assembly_rows(assembly_id, sort_order)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS estimate_flooring_catalog_assembly_rows")
    op.execute("DROP TABLE IF EXISTS estimate_flooring_catalog_assemblies")
