import { defineWorkspaceRegistry } from "../../../shared/workspace-contract";

export const doorsWorkbenchWorkspaceRegistry = defineWorkspaceRegistry({
  id: "calculator.doors-workbench",
  title: "Калькулятор дверей",
  description: "Рабочая область подбора, редактирования и расчета дверей объекта.",
  components: [
    {
      id: "doors-workbench.queue",
      type: "list",
      title: "Очередь дверей",
      description: "Список дверей объекта, выбор активной позиции и удаление строки.",
      dataKey: "calculator.doors.projectDoors",
      area: { x: 1, y: 1, w: 8, h: 18 },
      minArea: { w: 5, h: 8 },
      priority: 80,
      capabilities: {
        movable: false,
        resizable: true,
        deletable: false,
        copyable: false,
        collapsible: true,
      },
      children: [
        {
          id: "doors-workbench.queue.select-door",
          type: "button",
          role: "navigation",
          label: "Выбрать дверь",
          dataKey: "calculator.doors.selectedDoorId",
          critical: true,
        },
        {
          id: "doors-workbench.queue.delete-door",
          type: "button",
          role: "danger-action",
          label: "Удалить дверь",
          dataKey: "calculator.doors.projectDoors",
          critical: true,
          capabilities: { deletable: true },
        },
      ],
      source: {
        feature: "calculator/doors-workbench",
        file: "queue.tsx",
      },
    },
    {
      id: "doors-workbench.editor",
      type: "editor",
      title: "Редактор двери",
      description: "Основная форма выбранной двери: размеры, помещения, цены, заметки и сохранение.",
      dataKey: "calculator.doors.selectedDoor",
      area: { x: 9, y: 1, w: 14, h: 18 },
      minArea: { w: 8, h: 10 },
      priority: 100,
      capabilities: {
        movable: false,
        resizable: true,
        deletable: false,
        copyable: true,
        collapsible: false,
      },
      children: [
        {
          id: "doors-workbench.editor.title",
          type: "input",
          role: "field",
          label: "Название двери",
          dataKey: "calculator.doors.selectedDoor.title",
          critical: true,
        },
        {
          id: "doors-workbench.editor.kind",
          type: "select",
          role: "selector",
          label: "Тип двери",
          dataKey: "calculator.doors.selectedDoor.kind",
        },
        {
          id: "doors-workbench.editor.dimensions",
          type: "input",
          role: "field",
          label: "Размеры двери",
          dataKey: "calculator.doors.selectedDoor.dimensions",
          critical: true,
        },
        {
          id: "doors-workbench.editor.save",
          type: "button",
          role: "submit-action",
          label: "Сохранить дверь",
          critical: true,
        },
      ],
      relationships: [
        {
          type: "controls",
          targetId: "doors-workbench.components",
          note: "Выбранная дверь определяет список комплектующих.",
        },
        {
          type: "summarizes",
          targetId: "doors-workbench.summary",
        },
      ],
      source: {
        feature: "calculator/doors-workbench",
        file: "composers.tsx",
      },
    },
    {
      id: "doors-workbench.components",
      type: "list",
      title: "Комплект двери",
      description: "Список комплектующих выбранной двери и быстрые действия над позицией.",
      dataKey: "calculator.doors.selectedDoor.components",
      area: { x: 23, y: 1, w: 8, h: 18 },
      minArea: { w: 6, h: 8 },
      priority: 90,
      capabilities: {
        movable: false,
        resizable: true,
        deletable: false,
        copyable: false,
        collapsible: true,
      },
      children: [
        {
          id: "doors-workbench.components.quick-kit",
          type: "chip",
          role: "primary-action",
          label: "Быстрый комплект",
          dataKey: "calculator.doors.selectedDoor.components",
        },
        {
          id: "doors-workbench.components.delete-component",
          type: "button",
          role: "danger-action",
          label: "Удалить комплектующую",
          dataKey: "calculator.doors.selectedDoor.components",
          capabilities: { deletable: true },
        },
      ],
      source: {
        feature: "calculator/doors-workbench",
        file: "focus.tsx",
      },
    },
    {
      id: "doors-workbench.summary",
      type: "summary",
      title: "Итоги по двери",
      description: "Стоимость, закупка, продажа и монтаж по выбранной двери.",
      dataKey: "calculator.doors.selectedDoor.summary",
      area: { x: 1, y: 19, w: 30, h: 5 },
      minArea: { w: 10, h: 3 },
      priority: 70,
      capabilities: {
        movable: false,
        resizable: true,
        deletable: false,
        copyable: false,
        collapsible: true,
      },
      children: [
        {
          id: "doors-workbench.summary.total",
          type: "metric",
          role: "summary",
          label: "Итого",
          dataKey: "calculator.doors.selectedDoor.total",
          critical: true,
        },
      ],
      source: {
        feature: "calculator/doors-workbench",
        file: "stage.tsx",
      },
    },
  ],
});
