import type { DashboardProjectCardData, ProjectCardLedgerDocument, ProjectCardSourceFile } from "./project-model";

function sourceFile(id: string, fileName: string, uploadedAt: string, mimeType = "application/pdf"): ProjectCardSourceFile {
  return { id, fileName, uploadedAt, mimeType };
}

function ledgerDocument(
  id: string,
  kind: "invoice" | "act",
  title: string,
  date: string,
  amount: number,
  source: ProjectCardSourceFile,
  extractedByAi = true,
  verifiedByUser = true,
): ProjectCardLedgerDocument {
  return {
    id,
    kind,
    title,
    date,
    amount,
    sourceFile: source,
    extractedByAi,
    verifiedByUser,
  };
}

export const firstProjectCardMock: DashboardProjectCardData = {
  code: "ИБ / 22",
  name: "Карточка объекта",
  stageLabel: "В работе",
  stageTone: "active",
  areaM2: 173.6,
  estimateSource: "Смета калькулятора + ручной учёт",
  receivedTotal: 2446704,
  remainingTotal: 908094.16,
  deferredTotal: 0,
  plannedTotal: 163000,
  actualTotal: 1538609.84,
  workPerM2: 10770.55,
  materialsPerM2: 8859.14,
  plannedMarginPercent: 30,
  nextDeliveryLabel: "10.05 сб",
  expenses: [
    { label: "Работы", amount: 560668.72, tone: "cyan" },
    { label: "Материалы", amount: 460675.12, tone: "emerald" },
    { label: "Услуги", amount: 25000, tone: "amber" },
    { label: "Техника", amount: 143940, tone: "rose" },
    { label: "Мебель", amount: 43200, tone: "slate" },
    { label: "Двери", amount: 67766, tone: "slate" },
  ],
  advances: [{ id: "advance-main", title: "Аванс", amount: 2446704, date: "08.02.2026", status: "paid" }],
  ledgerEntries: [
    {
      id: "ledger-rough-work",
      category: "Работы",
      item: "Черновые работы",
      owner: "Прохоров Д.",
      counterparty: "ООО Баумастер Рус",
      status: "paid",
      invoiceDocument: ledgerDocument(
        "invoice-rough-work",
        "invoice",
        "Счёт / черновые / 01",
        "2026-03-16",
        320000,
        sourceFile("source-invoice-rough-work", "Счёт_черновые_01.pdf", "2026-03-16T10:20:00"),
      ),
      actDocument: ledgerDocument(
        "act-rough-work",
        "act",
        "Акт / черновые / 01",
        "2026-03-22",
        318400,
        sourceFile("source-act-rough-work", "Акт_черновые_01.pdf", "2026-03-22T17:45:00"),
      ),
      planAmount: 320000,
      actualAmount: 318400,
      controlDate: "2026-03-22",
    },
    {
      id: "ledger-materials-clean",
      category: "Материалы",
      item: "Чистовые материалы",
      owner: "Прохоров Д.",
      counterparty: "ООО Сан-Склад",
      status: "waiting-payment",
      invoiceDocument: ledgerDocument(
        "invoice-materials-clean",
        "invoice",
        "Счёт / материалы / 02",
        "2026-04-19",
        620000,
        sourceFile("source-invoice-materials-clean", "Счёт_материалы_02.pdf", "2026-04-19T11:15:00"),
      ),
      actDocument: null,
      planAmount: 620000,
      actualAmount: 0,
      controlDate: "2026-04-25",
    },
    {
      id: "ledger-doors",
      category: "Двери",
      item: "Дверной блок и фурнитура",
      owner: "Прохоров В.",
      counterparty: "ИП Двери Шоурум",
      status: "invoice",
      invoiceDocument: ledgerDocument(
        "invoice-doors",
        "invoice",
        "Счёт / двери / 01",
        "2026-04-28",
        67766,
        sourceFile("source-invoice-doors", "Счёт_двери_01.pdf", "2026-04-28T09:40:00"),
      ),
      actDocument: null,
      planAmount: 67766,
      actualAmount: 0,
      controlDate: "2026-05-03",
    },
    {
      id: "ledger-services",
      category: "Услуги",
      item: "Вывоз мусора и логистика",
      owner: "Меркушин Б.",
      counterparty: "ООО Сервис Снаб",
      status: "completed",
      invoiceDocument: ledgerDocument(
        "invoice-services",
        "invoice",
        "Счёт / логистика / 03",
        "2026-03-05",
        25000,
        sourceFile("source-invoice-services", "Счёт_логистика_03.pdf", "2026-03-05T12:30:00"),
      ),
      actDocument: ledgerDocument(
        "act-services",
        "act",
        "Акт / логистика / 03",
        "2026-03-10",
        25000,
        sourceFile("source-act-services", "Акт_логистика_03.pdf", "2026-03-10T18:10:00"),
      ),
      planAmount: 25000,
      actualAmount: 25000,
      controlDate: "2026-03-10",
    },
    {
      id: "ledger-tech",
      category: "Техника",
      item: "Аренда подъёмника",
      owner: "Меркушин Б.",
      counterparty: "ООО ТехНайм",
      status: "planned",
      invoiceDocument: null,
      actDocument: null,
      planAmount: 143940,
      actualAmount: 0,
      controlDate: "2026-05-10",
    },
    {
      id: "ledger-furniture",
      category: "Мебель",
      item: "Встроенная мебель",
      owner: "Прохоров Г.",
      counterparty: "ООО Мебель Ателье",
      status: "invoice",
      invoiceDocument: ledgerDocument(
        "invoice-furniture",
        "invoice",
        "Счёт / мебель / 01",
        "2026-05-08",
        43200,
        sourceFile("source-invoice-furniture", "Счёт_мебель_01.pdf", "2026-05-08T14:05:00"),
      ),
      actDocument: null,
      planAmount: 43200,
      actualAmount: 0,
      controlDate: "2026-05-16",
    },
  ],
  contract: {
    fileName: "ДОГОВОР ПОДРЯДА 01-02-26.pdf",
    title: "Договор подряда на ремонт и комплектацию объекта",
    number: "ДОГОВОР ПОДРЯДА № 01/02/26",
    signedAt: "2026-02-08",
    startDate: "2026-02-10",
    plannedEndDate: "2026-08-30",
    amount: 2446704,
    advanceTerms: "Первичный аванс 30%, далее оплата по выставленным счетам и актам этапов.",
    extractionStatus: "review",
    milestones: [
      {
        id: "contract-invoice-2",
        kind: "invoice",
        title: "Выставить второй счёт на материалы",
        plannedDate: "2026-04-20",
        amount: 620000,
        note: "После подтверждения поставки чистовых материалов.",
        status: "due",
      },
      {
        id: "contract-payment-2",
        kind: "payment",
        title: "Получить второй аванс от заказчика",
        plannedDate: "2026-04-25",
        amount: 620000,
        note: "Оплата привязана к счёту №2.",
        status: "upcoming",
      },
      {
        id: "contract-deadline-rough",
        kind: "deadline",
        title: "Закрыть этап черновых работ",
        plannedDate: "2026-05-12",
        note: "Нужен акт и фотофиксация перед следующим этапом.",
        status: "upcoming",
      },
      {
        id: "contract-payment-1",
        kind: "payment",
        title: "Первичный аванс получен",
        plannedDate: "2026-02-08",
        amount: 2446704,
        status: "completed",
      },
    ],
  },
};
