"""Схемы admin API, разложенные по доменам."""

from supply_bot.admin_api.schemas.auth import AdminLoginPayload
from supply_bot.admin_api.schemas.calculator import (
    CalculatorDoorCatalogPayload,
    CalculatorDoorComponentCatalogPayload,
    CalculatorFloorSectionPayload,
    CalculatorOpeningPayload,
    CalculatorProjectCreatePayload,
    CalculatorProjectDoorComponentPayload,
    CalculatorProjectDoorPayload,
    CalculatorProjectUpdatePayload,
    CalculatorRoomCreatePayload,
    CalculatorRoomUpdatePayload,
    CalculatorWallFinishCoveringPayload,
    CalculatorWallFinishLayoutPayload,
    CalculatorWallFinishPreparationPayload,
    CalculatorWallFinishRoomPayload,
    CalculatorWallFinishUpdatePayload,
    CalculatorWarmFloorRoomPayload,
    CalculatorWarmFloorUpdatePayload,
)
from supply_bot.admin_api.schemas.calculator_flooring import (
    CalculatorFlooringCoveringPayload,
    CalculatorFlooringLayoutPayload,
    CalculatorFlooringPreparationPayload,
    CalculatorFlooringRoomPayload,
    CalculatorFlooringUpdatePayload,
)
from supply_bot.admin_api.schemas.materials import (
    AliasCreatePayload,
    FamilyCreatePayload,
    SkuCreatePayload,
    VariantCreatePayload,
)
from supply_bot.admin_api.schemas.projects import (
    ProjectAdvanceCreatePayload,
    ProjectContractMilestonePayload,
    ProjectContractMilestoneUpdatePayload,
    ProjectContractUpdatePayload,
    ProjectCreatePayload,
    ProjectLedgerCounterpartyPayload,
    ProjectLedgerDocumentUpdatePayload,
    ProjectLedgerEntryCreatePayload,
    ProjectLedgerEntryUpdatePayload,
    ProjectUpdatePayload,
)
from supply_bot.admin_api.schemas.requests import (
    RequestActionResult,
    RequestDeliveryPayload,
    RequestItemPayload,
    RequestStatusPayload,
)
from supply_bot.admin_api.schemas.support import DeliverySettingsPayload

__all__ = [
    "AdminLoginPayload",
    "AliasCreatePayload",
    "CalculatorDoorCatalogPayload",
    "CalculatorDoorComponentCatalogPayload",
    "CalculatorFloorSectionPayload",
    "CalculatorFlooringCoveringPayload",
    "CalculatorFlooringLayoutPayload",
    "CalculatorFlooringPreparationPayload",
    "CalculatorFlooringRoomPayload",
    "CalculatorFlooringUpdatePayload",
    "CalculatorOpeningPayload",
    "CalculatorProjectCreatePayload",
    "CalculatorProjectUpdatePayload",
    "CalculatorProjectDoorComponentPayload",
    "CalculatorProjectDoorPayload",
    "CalculatorRoomCreatePayload",
    "CalculatorRoomUpdatePayload",
    "CalculatorWarmFloorRoomPayload",
    "CalculatorWarmFloorUpdatePayload",
    "CalculatorWallFinishCoveringPayload",
    "CalculatorWallFinishLayoutPayload",
    "CalculatorWallFinishPreparationPayload",
    "CalculatorWallFinishRoomPayload",
    "CalculatorWallFinishUpdatePayload",
    "DeliverySettingsPayload",
    "FamilyCreatePayload",
    "ProjectAdvanceCreatePayload",
    "ProjectContractMilestonePayload",
    "ProjectContractMilestoneUpdatePayload",
    "ProjectContractUpdatePayload",
    "ProjectCreatePayload",
    "ProjectLedgerCounterpartyPayload",
    "ProjectLedgerDocumentUpdatePayload",
    "ProjectLedgerEntryCreatePayload",
    "ProjectLedgerEntryUpdatePayload",
    "ProjectUpdatePayload",
    "RequestActionResult",
    "RequestDeliveryPayload",
    "RequestItemPayload",
    "RequestStatusPayload",
    "SkuCreatePayload",
    "VariantCreatePayload",
]
