from __future__ import annotations

DECISION_JSON_SCHEMA: dict = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "reply_text",
        "intent",
        "confidence",
        "loop_detected",
        "actions",
        "missing_branches",
        "ready_for_confirmation",
        "notes",
    ],
    "properties": {
        "reply_text": {"type": "string"},
        "intent": {
            "type": "string",
            "enum": [
                "start_request",
                "add_item",
                "update_item",
                "remove_item",
                "clarify_item",
                "answer_clarification",
                "repeat_summary",
                "update_delivery",
                "recover_request",
                "confirm_request",
                "cancel_request",
                "offtopic",
                "unknown",
            ],
        },
        "confidence": {"type": "number", "minimum": 0, "maximum": 1},
        "loop_detected": {"type": "boolean"},
        "actions": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["type"],
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": [
                            "add_item",
                            "update_item",
                            "remove_item",
                            "set_delivery",
                            "set_delivery_date",
                            "set_delivery_time",
                            "propose_delivery_slot",
                            "rebuild_draft",
                            "request_clarification",
                            "show_summary",
                            "confirm_request",
                            "cancel_request",
                            "no_op",
                        ],
                    },
                    "target_item_index": {"type": ["integer", "null"], "minimum": 1},
                    "target_item_match": {"type": ["string", "null"]},
                    "raw_text": {"type": ["string", "null"]},
                    "normalized_name": {"type": ["string", "null"]},
                    "catalog_family": {"type": ["string", "null"]},
                    "catalog_variant": {"type": ["string", "null"]},
                    "quantity": {"type": ["number", "null"]},
                    "unit": {"type": ["string", "null"]},
                    "thickness_mm": {"type": ["number", "null"]},
                    "length_mm": {"type": ["number", "null"]},
                    "width_mm": {"type": ["number", "null"]},
                    "note": {"type": ["string", "null"]},
                    "delivery_date": {"type": ["string", "null"]},
                    "delivery_time": {"type": ["string", "null"]},
                    "question": {"type": ["string", "null"]},
                    "needs_confirmation": {"type": ["boolean", "null"]},
                    "reason": {"type": ["string", "null"]},
                    "replacement_items": {
                        "type": ["array", "null"],
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["raw_text"],
                            "properties": {
                                "raw_text": {"type": "string"},
                                "normalized_name": {"type": ["string", "null"]},
                                "catalog_family": {"type": ["string", "null"]},
                                "catalog_variant": {"type": ["string", "null"]},
                                "quantity": {"type": ["number", "null"]},
                                "unit": {"type": ["string", "null"]},
                                "thickness_mm": {"type": ["number", "null"]},
                                "length_mm": {"type": ["number", "null"]},
                                "width_mm": {"type": ["number", "null"]},
                                "note": {"type": ["string", "null"]},
                                "needs_confirmation": {"type": ["boolean", "null"]},
                            },
                        },
                    },
                    "replacement_delivery_date": {"type": ["string", "null"]},
                    "replacement_delivery_time": {"type": ["string", "null"]},
                },
            },
        },
        "missing_branches": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "items",
                    "item_variant",
                    "item_quantity",
                    "item_specs",
                    "delivery_date",
                    "delivery_time",
                    "confirmation",
                ],
            },
        },
        "ready_for_confirmation": {"type": "boolean"},
        "notes": {"type": "string"},
    },
}
