"""Совместимый фасад доменного слоя проектов.

Раньше весь доменный код жил здесь.
Теперь реальная логика разнесена по подпакету `projects.domain`,
а этот файл оставлен как стабильная точка импорта для остального кода.
"""

from __future__ import annotations

from supply_bot.projects.domain.common import (
    ALLOWED_PROJECT_ADVANCE_STATUSES,
    ALLOWED_PROJECT_CONTRACT_EXTRACTION_STATUSES,
    ALLOWED_PROJECT_CONTRACT_MILESTONE_KINDS,
    ALLOWED_PROJECT_CONTRACT_MILESTONE_STATUSES,
    ALLOWED_PROJECT_LEDGER_STATUSES,
    ALLOWED_PROJECT_STAGE_TONES,
    DEFAULT_PROJECT_ESTIMATE_SOURCE,
    DEFAULT_PROJECT_NAME,
    DEFAULT_PROJECT_STAGE_LABEL,
    DEFAULT_PROJECT_STAGE_TONE,
    ProjectValidationError,
    build_default_project_code,
    default_project_contract_milestone_status,
    document_title_for_kind,
    normalize_project_date,
    normalize_project_name,
    normalize_project_stage_label,
    normalize_project_stage_tone,
    normalize_project_text,
    validate_project_metric,
)
from supply_bot.projects.domain.contract import (
    build_extracted_project_contract_values,
    build_project_contract_milestone_payload,
    build_project_contract_milestone_update_values,
    build_project_contract_milestones_values,
    build_project_contract_payload,
    build_project_contract_upload_values,
    build_project_contract_upsert_values,
    normalize_project_contract_extraction_status,
    normalize_project_contract_milestone_kind,
    normalize_project_contract_milestone_status,
)
from supply_bot.projects.domain.ledger import (
    build_project_document_update_values,
    build_project_ledger_create_values,
    build_project_ledger_document_create_values,
    build_project_ledger_document_payload,
    build_project_ledger_entry_payload,
    build_project_ledger_update_values,
    normalize_project_ledger_status,
)
from supply_bot.projects.domain.project import (
    build_project_advance_create_values,
    build_project_advance_payload,
    build_project_create_values,
    build_project_payload,
    build_project_update_values,
    normalize_project_advance_status,
)

__all__ = [
    "ALLOWED_PROJECT_ADVANCE_STATUSES",
    "ALLOWED_PROJECT_CONTRACT_EXTRACTION_STATUSES",
    "ALLOWED_PROJECT_CONTRACT_MILESTONE_KINDS",
    "ALLOWED_PROJECT_CONTRACT_MILESTONE_STATUSES",
    "ALLOWED_PROJECT_LEDGER_STATUSES",
    "ALLOWED_PROJECT_STAGE_TONES",
    "DEFAULT_PROJECT_ESTIMATE_SOURCE",
    "DEFAULT_PROJECT_NAME",
    "DEFAULT_PROJECT_STAGE_LABEL",
    "DEFAULT_PROJECT_STAGE_TONE",
    "ProjectValidationError",
    "build_default_project_code",
    "build_extracted_project_contract_values",
    "build_project_advance_create_values",
    "build_project_advance_payload",
    "build_project_contract_milestone_payload",
    "build_project_contract_milestone_update_values",
    "build_project_contract_milestones_values",
    "build_project_contract_payload",
    "build_project_contract_upload_values",
    "build_project_contract_upsert_values",
    "build_project_create_values",
    "build_project_document_update_values",
    "build_project_ledger_create_values",
    "build_project_ledger_document_create_values",
    "build_project_ledger_document_payload",
    "build_project_ledger_entry_payload",
    "build_project_ledger_update_values",
    "build_project_payload",
    "build_project_update_values",
    "default_project_contract_milestone_status",
    "document_title_for_kind",
    "normalize_project_advance_status",
    "normalize_project_contract_extraction_status",
    "normalize_project_contract_milestone_kind",
    "normalize_project_contract_milestone_status",
    "normalize_project_date",
    "normalize_project_ledger_status",
    "normalize_project_name",
    "normalize_project_stage_label",
    "normalize_project_stage_tone",
    "normalize_project_text",
    "validate_project_metric",
]
